[build]
builder = "DOCKERFILE"
dockerfilePath = "docker-compose.prod.yml"

[deploy]
startCommand = "docker-compose -f docker-compose.prod.yml up"
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
